<a href="https://colab.research.google.com/github/Aniruddhan15/DEEP-LEARNING-TUTORIALS/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.36999452, -1.42503419, -0.43496369, ..., -0.9562028 ,
        -0.94880343, -0.82291783],
       [-0.98760679,  0.22128234, -0.94349899, ..., -0.46470495,
        -0.47209036,  0.14546684],
       [ 0.70657733,  0.17825619,  0.59975584, ..., -0.44388392,
         2.86490114, -0.4390341 ],
       ...,
       [-1.25193351, -0.54865937, -1.23080707, ..., -0.96106611,
        -0.58804759,  0.01913222],
       [ 1.25619559,  1.2901426 ,  1.32623485, ...,  1.03684076,
         0.87913352,  0.7315944 ],
       [ 0.09463123, -0.01649377,  0.0723403 , ..., -0.31363851,
        -0.68789965, -0.52578748]])

In [9]:
y_train

287    B
269    B
489    M
338    B
3      M
      ..
322    B
34     M
110    B
30     M
448    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0])

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train.shape

(455, 30)

In [14]:
X_train_tensor

tensor([[-0.3700, -1.4250, -0.4350,  ..., -0.9562, -0.9488, -0.8229],
        [-0.9876,  0.2213, -0.9435,  ..., -0.4647, -0.4721,  0.1455],
        [ 0.7066,  0.1783,  0.5998,  ..., -0.4439,  2.8649, -0.4390],
        ...,
        [-1.2519, -0.5487, -1.2308,  ..., -0.9611, -0.5880,  0.0191],
        [ 1.2562,  1.2901,  1.3262,  ...,  1.0368,  0.8791,  0.7316],
        [ 0.0946, -0.0165,  0.0723,  ..., -0.3136, -0.6879, -0.5258]],
       dtype=torch.float64)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

# My Neural Network

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
num_epochs=20
lr = 0.01

In [22]:
class NN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    sum = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(sum)
    return y_pred

In [20]:
model = NN(X_train_tensor)
model.weights

tensor([[0.5074],
        [0.9481],
        [0.2177],
        [0.8188],
        [0.4355],
        [0.0383],
        [0.1963],
        [0.5682],
        [0.5715],
        [0.8507],
        [0.2663],
        [0.0108],
        [0.9696],
        [0.2849],
        [0.9275],
        [0.8098],
        [0.5643],
        [0.5630],
        [0.7310],
        [0.1583],
        [0.4217],
        [0.3246],
        [0.3305],
        [0.6267],
        [0.1538],
        [0.1559],
        [0.5685],
        [0.4956],
        [0.9476],
        [0.2513]], dtype=torch.float64, requires_grad=True)

In [21]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

### Defining the model

In [23]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)


  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [24]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [27]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.5246308995260587
Epoch: 2, Loss: 3.387635230314328
Epoch: 3, Loss: 3.246685463784199
Epoch: 4, Loss: 3.104174675192834
Epoch: 5, Loss: 2.957873316277345
Epoch: 6, Loss: 2.804589235076959
Epoch: 7, Loss: 2.651744842454887
Epoch: 8, Loss: 2.4927019178954786
Epoch: 9, Loss: 2.3304648691416805
Epoch: 10, Loss: 2.164547654333961
Epoch: 11, Loss: 2.0035994852034418
Epoch: 12, Loss: 1.84163827416566
Epoch: 13, Loss: 1.6853477631925036
Epoch: 14, Loss: 1.5373314553043937
Epoch: 15, Loss: 1.398554891648077
Epoch: 16, Loss: 1.2700642138310385
Epoch: 17, Loss: 1.1577261661097047
Epoch: 18, Loss: 1.0627417415478628
Epoch: 19, Loss: 0.9854168426230636
Epoch: 20, Loss: 0.9248517727099042
Epoch: 21, Loss: 0.8789677432506766
Epoch: 22, Loss: 0.8449470629272448
Epoch: 23, Loss: 0.8198609530338049
Epoch: 24, Loss: 0.8011526347232244
Epoch: 25, Loss: 0.7868399357470084

In [ ]:
model.bias

tensor([-0.0940], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6378886103630066